# Generated by Django 3.0.5 on 2020-04-23 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtopic',
            old_name='topicId',
            new_name='topic',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='sectionId',
            new_name='section',
        ),
    ]
